# Result of the point cloud detection in sequential given to the color detection
# In each list, the same index corresponds to same detected object

# Lists containing the coordinates of each point in the 3D point cloud reference
float32[] Xlist
float32[] Ylist
float32[] Zlist

# Lists containing the RGB values of each point
float32[] Rlist
float32[] Glist
float32[] Blist

# List containing the ID of the cluster of the corresponding point
float32[] Clusters
